function [trans] = To2i(W, i, w)
    % Transformation matrix from orbital frame to inertial frame
    % W: Right Ascension of Ascending Node [rad]
    % i: Inclination [rad]
    % w: Argument of Perigee [rad]
    
    trans = [-sin(W)*cos(i)*sin(w) + cos(W)*cos(w), ...
             -sin(W)*cos(i)*cos(w) - cos(W)*sin(w), ...
              sin(W)*sin(i);...
             
              cos(W)*cos(i)*sin(w) + sin(W)*cos(w), ...
              cos(W)*cos(i)*cos(w) - sin(W)*sin(w), ...
             -cos(W)*sin(i);...
             
              sin(i)*sin(w), ...
              sin(i)*cos(w), ...
              cos(i)];
end